add support bionic
canonical/charm-lldpd pull request #29
Opened 2024-07-18 05:56 UTC by xtrusia

While I'm testing current ops, there was some issues in ops library. and I asked ops team to take a look at that.

They helped me to support bionic with current code.

I create this pull request with their code.

Thanks a lot.

2024-07-20 23:39 UTC, xtrusia commented
@wolsen Although there are issue with signed off by but could you please review this one?
I've checked it is working with Bionic

2024-07-23 13:08 UTC, wolsen commented
Note the Signed-off-by DCO check are failing because the commits are not signed of with -s when doing git commit. A couple of comments in-line, but overall looking good.

2024-07-23 13:08 UTC, wolsen requested changes

2024-07-23 13:08 UTC, wolsen commented on tox.ini
> +    # FIXME: there's no LIB{PATCH,API} in src/charm.py, should there be?
No, this would be in the charm libs but the charm doesn't have any. This can likely be removed

2024-07-23 13:08 UTC, wolsen commented on .github/workflows/ci.yaml
> +  push:
Let's go ahead and remove this per the comment

2024-07-24 00:28 UTC, xtrusia commented
> Note the Signed-off-by DCO check are failing because the commits are not signed of with -s when doing git commit. A couple of comments in-line, but overall looking good.

Thanks a lot!

2024-08-08 01:40 UTC, wolsen approved these changes

2024-08-08 01:40 UTC, merged